using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using UserManagementApp.Models;
using UserManagementApp.Repositories;

namespace UserManagementApp.Views
{
    public partial class GridControlDevEX<T> : Form where T : class
    {
        IRepository<T> repository;
        public GridControlDevEX(IRepository<T> repository)
        {
            this.repository = repository;
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            userGridControl.DataSource = repository.GetList();//new System.ComponentModel.BindingList<UserManagementApp.Models.User>() /* TODO: Assign the real data here.*/;
        }

        private void ModifyBtn_Click(object sender, EventArgs e)
        {
            if (userListGridView.SelectedRowsCount != 0)
            {
                User user = (repository as IRepository<User>)
                    .GetList()
                    .ToList()[userListGridView.GetSelectedRows().First()];// as User;
                DetailForm<User> detailForm = new DetailForm<User>(user, repository as UserRepository);
                detailForm.StartPosition = FormStartPosition.CenterParent;
                //detailForm.TopMost = true;
                detailForm.ShowDialog();
            }
        }

        private void XMLExportBtn_Click(object sender, EventArgs e)
        {
            if (saveFileDialog.ShowDialog() == DialogResult.OK)
            {
                (repository as IExport).ExportDataList(filePath: saveFileDialog.FileName);
            }
        }
    }
}
